### ISSUE TITLE
Variance partitioning plot

### ISSUE THREAD

**Issue by ushukla89** [hmsc-r/HMSC#1]
Hello,
I was just going through the model outputs.
There is a small component missing in the plot function. 
It does not calculate/show the R2 of traits when using the plotVariancePartitioning() function.

**Comment by ovaskain** [comment]
This is because R2 for traits is now calculated in two ways: VP$R2T$Beta tells how much traits explain out of variation among species in their response to each covariate (this is new), and VP$R2T$Y tells how much traits explain out of variation in species occurrences (this is what used to be there). As there are many numbers related to R2T, they are not put to the plot title. See pages 9-10 in vignette_3_multivariate_high.pdf  for more  details.
