### ISSUE TITLE
Using both spatial and temporal sampling units in random effects

### ISSUE THREAD

**Issue by andburch** [hmsc-r/HMSC#103]
I'm trying to include random effects of both space (XY) and time (year) simultaneously, but nothing seems to work. Essentially, I'm just trying to run the Finnish bird data through the model provided in the book/documentation, but include ALL the data (not just from 2014).

In the examples, the `studyDesign` variable is just a column of "sampling unit" names; the same names which are included as row names in the XY dataset used to make the spatial random effects. However, when you sample from the same sites for multiple years, the row names (and the column in `studyDesign`) can't refer to the sampling locations anymore (row names must be unique). Even if you change the sampling unit names to be year-location pairs (e.g. `"route2.year2010"`), you still get errors because `HmsRandomLevel()` wants all spatial data to be unique:  `"... sData locations must be unique"`

But each location has multiple time points associated with it, and each time point has multiple sites sampled. I'm not sure how you can tie these all together.

**How can you set up the `studyDesign` and random effects in the Finnish bird study to include spatial and temporal random effects at the same time?**

**Comment by ovaskain** [comment]
Hi,

Let’s assume that you have 100 spatial locations (column “route” in studyDesign) and 20 time-points (column “year” in studyDesign), so in total 2000 space-time pairs (column “route.year” in studyDesign). In the factor studyDesign$route, there are 2000 values that represent 100 levels. When you define HmscRandomLevel for space, for sData (or units, if you assume unstructured random effect) you will bring those 100 levels only once, so for that repeating values are not possible. You connect them to the studyDesign route by having the levels as the rownames of the sData. Same holds with temporal random effect, or any kind of random effect: in studyDesign the levels can repeat, but HmscRandomLevel is defined for the unique values = the levels.

Best,

Otso

From: Andrew T Burchill ***@***.***>
Sent: maanantai 21. kesäkuuta 2021 21:12
To: hmsc-r/HMSC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hmsc-r/HMSC] Using both spatial and temporal sampling units in random effects (#103)


I'm trying to include random effects of both space (XY) and time (year) simultaneously, but nothing seems to work. Essentially, I'm just trying to run the Finnish bird data through the model provided in the book/documentation, but include ALL the data (not just from 2014).

In the examples, the studyDesign variable is just a column of "sampling unit" names; the same names which are included as row names in the XY dataset used to make the spatial random effects. However, when you sample from the same sites for multiple years, the row names (and the column in studyDesign) can't refer to the sampling locations anymore (row names must be unique). Even if you change the sampling unit names to be year-location pairs (e.g. "route2.year2010"), you still get errors because HmsRandomLevel() wants all spatial data to be unique: "... sData locations must be unique"

But each location has multiple time points associated with it, and each time point has multiple sites sampled. I'm not sure how you can tie these all together.

How can you set up the studyDesign and random effects in the Finnish bird study to include spatial and temporal random effects at the same time?

**Comment by andburch** [comment]
Okay, that's what I was thinking, but the code is not working.

My studyDesign has `time` as the year and `ident` as the location, with the row names being their combination (same row names as Y):
```
            time   ident
CHLR-011996 1996 CHLR-01
CHLR-011997 1997 CHLR-01
CHLR-011998 1998 CHLR-01
CHLR-011999 1999 CHLR-01
CHLR-012000 2000 CHLR-01
CHLR-012001 2001 CHLR-01
. . . 
```

My spatial XY data frame that generates the spatial random effect is this (I used fake data to try and avoid the error mentioned later, but it didn't help):
```
        x-coordinate y-coordinate
CHLR-01            1            1
CHLR-02            2            2
CHLR-03            3            3
CHLR-04            4            4
CHLR-05            5            5
CHLR-06            6            6
. . . 
```

My temporal data frame used to make the temporal random effect is this: 

```
        num
1996     1
1997     2
1998     3
1999     4
2000     5
2001     6
. . . 
```

However, when I try to run `sampleMcmc()`, I get this error: `Error in computeDataParameters(hM) :   spatial distance matrix is non-metric or has duplicated points`. This is odd, because it only happens when the spatial random effect is included; it doesn't happen when I only include the temporal random effect. Also, I used fake XY data to make SURE there are no "non-metric" or duplicated points, yet it still happens.... What could be going wrong?

**Ah, as I was writing this, I checked the dimensions of my data frames.** `studyDesign` has 3106 rows, `space` has 128, and `time` has 24. But 128*24 = 3072. There are a few location*year pairs from the total possible sampling units that were not recorded over the last 30 years. Could that be the issue? Is there a way to correct this?

**Comment by ovaskain** [comment]
Hi Andrew,

Looks like some trivial issue that may be hard to spot if you don’t know what you are exactly looking at. Can you email me the data (e.g. as RData file) and Hmsc script that reads in the data and constructs the Hmsc object (so should be just couple of lines) and produces the error, so I will have a look.

O2

**Comment by andburch** [comment]
For posterity and anyone else with the same problem, @ovaskain figured it out. 

> Here one issue: 128 is not the same as 130:
> ```
> >rL.spatial
> Hmsc random level object with 128 units. Spatial dimensionality is 2 and number of covariates is 0.
> 
> > length(levels(studyDesign$ident))
> [1] 130
> ```

To select the set of sampling locations used each year, I subsetted the data frame and filtered it by a specific year. I naively and randomly chose one of the few years in which some locations were not sampled. You are a hero.
