### ISSUE TITLE
HmscRandomLevel() not parsing properly when using "units = "

### ISSUE THREAD

**Issue by andburch** [hmsc-r/HMSC#111]
Sorry for raising so many concerns, but I've been finding that specifying `units =` in `HmscRandomLevel()` is not working as it should.
For example, this is code copied directly from the book:
```
set.seed(6)
n = 120 
# . . .
plot.id = sample(1:np, n, replace = TRUE) 
# . . .

plot.id = as.factor(plot.id)
sample.id = as.factor(1:n) 
studyDesign = data.frame(sample = sample.id, plot = plot.id)
rL = HmscRandomLevel(units = studyDesign$plot)

```
When we examine `studyDesign` we see 120 samples that are divided into 12 plots. Thus, the this random level variable for "plots" should have 12 levels. However, this is what `rL` returns: `Hmsc random level object with 120 units. Spatial dimensionality is 0 and number of covariates is 0.` Instead of the 12 levels pertaining to the plots, you get **120 units**, which doesn't seem right.

Alternatively, we can try specifying the random level using a data frame of the plot values (keeping the sample.id as the rownames) and we get another, different result with only **1 unit**:

```
> rL.dataframe = HmscRandomLevel(units = data.frame(plots=studyDesign$plot))

Hmsc random level object with 1 units. Spatial dimensionality is 0 and number of covariates is 0.
```                               

If we only use the unique values of `plot` we get a THIRD result with **12 units**:

```
> rL.unique = HmscRandomLevel(units = unique(studyDesign$plot))

Hmsc random level object with 12 units. Spatial dimensionality is 0 and number of covariates is 0.
```

This seems like a problem: why do they all return different numbers of "units"? Additionally, which is the correct specification?

### Comparisons to HmscRandomLevel() when specifying `sData`

As per the team's instructions for formatting spatial/temporally explicit random levels, I thought the inputs to HmscRandomLevel() were supposed to have row names corresponding to the unit levels of a column found in `studyDesign`. Below is what I used to make a random level from my own analysis with X and Y coordinates corresponding to unique locations.

```
        x-coordinate y-coordinate
CHLR-01     376874.5      5320821
CHLR-02     376671.5      5321160
CHLR-03     376269.5      5321094
CHLR-05     375578.5      5320705
. . .
```
When specified like this, the random level object correctly reports 120 units/levels for my 120 unique spatial points, even though I have many more sampling units than just 120. 

I logically thought that non-spatial random effects should be specified in a similar way, such as:
```
   plot.factors
12      p.12
6        p.6
9        p.9
4        p.4
10      p.10
3        p.3
1        p.1
. . .
```
But this result returns the `Hmsc random level object with 1 units`, which is clearly less than the actual 12 units.

**Comment by ovaskain** [comment]
Hi Andrew,

The correct version is

rL = HmscRandomLevel(units = unique(studyDesign$plot))

or alternatively

rL = HmscRandomLevel(units = levels(studyDesign$plot))

You are right that the example in the book is without “levels” and thus I see it causes confusion. Probably the function worked a bit differently when we wrote the book and specifying “levels” was not necessary at that time. Sorry for that.

Otso

From: Andrew T Burchill ***@***.***>
Sent: tiistai 27. heinäkuuta 2021 21:50
To: hmsc-r/HMSC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hmsc-r/HMSC] HmscRandomLevel() not parsing properly when using "units = " (#111)


Sorry for raising so many concerns, but I've been finding that specifying units = in HmscRandomLevel() is not working as it should.
For example, this is code copied directly from the book:

set.seed(6)

n = 120

# . . .

plot.id = sample(1:np, n, replace = TRUE)

# . . .



plot.id = as.factor(plot.id)

sample.id = as.factor(1:n)

studyDesign = data.frame(sample = sample.id, plot = plot.id)

rL = HmscRandomLevel(units = studyDesign$plot)



When we examine studyDesign we see 120 samples that are divided into 12 plots. Thus, the this random level variable for "plots" should have 12 levels. However, this is what rL returns: Hmsc random level object with 120 units. Spatial dimensionality is 0 and number of covariates is 0. Instead of the 12 levels pertaining to the plots, you get 120 units, which doesn't seem right.

Alternatively, we can try specifying the random level using a data frame of the plot values (keeping the sample.id as the rownames) and we get another, different result with only 1 unit:

> rL.dataframe = HmscRandomLevel(units = data.frame(plots=studyDesign$plot))



Hmsc random level object with 1 units. Spatial dimensionality is 0 and number of covariates is 0.

If we only use the unique values of plot we get a THIRD result with 12 units:

> rL.unique = HmscRandomLevel(units = unique(studyDesign$plot))



Hmsc random level object with 12 units. Spatial dimensionality is 0 and number of covariates is 0.

This seems like a problem: why do they all return different numbers of "units"? Additionally, which is the correct specification?

Comparisons to HmscRandomLevel() when specifying sData

As per the team's instructions for formatting spatial/temporally explicit random levels, I thought the inputs to HmscRandomLevel() were supposed to have row names corresponding to the unit levels of a column found in studyDesign. Below is what I used to make a random level from my own analysis with X and Y coordinates corresponding to unique locations.

        x-coordinate y-coordinate

CHLR-01     376874.5      5320821

CHLR-02     376671.5      5321160

CHLR-03     376269.5      5321094

CHLR-05     375578.5      5320705

. . .

I logically thought that non-spatial random effects should be specified in a similar way, such as:

   plot.factors

12      p.12

6        p.6

9        p.9

4        p.4

10      p.10

3        p.3

1        p.1

. . .

But this result returns the Hmsc random level object with 1 units.

**Comment by andburch** [comment]
You all are heroes. The fact that these issues on Github get addressed is absolutely amazing, and I'm incredibly thankful.
