### ISSUE TITLE
Issue in prediction of spatial models

### ISSUE THREAD

**Issue by Breezezcl** [hmsc-r/HMSC#19]
I think this line may result in NA when the names of units in fitted model are not included in the 'ranLevels' for prediction.  

https://github.com/hmsc-r/HMSC/blob/3f617bda1e6d1bf6f8995fbb57b95bab0269e35d/R/predictLatentFactor.R#L95

A combination of 'rL$s' in the ranLevels of both fitted objective and prediction data may be needed here.

**Comment by gtikhonov** [comment]
Yes, you are completely correct. However this is not a bug, but a design feature:
Currently the design assumes that you provide a full list of spatial sites at the moment of defining the model. Then you use some of them (not necessarily all) when training the model. Finally, you make the predictions also referring to the sites from this list. 

Such design has certain pros, e.g. it allows to specify the structure of spatial random level only once, which is good since we found that it is a common source of issues. On the ther hand, this design requires the user to know the locations for prediction beforehand. But currently there are no plans to change this in nearest future.
