### ISSUE TITLE
Hmsc.Rd blocked

### ISSUE THREAD

**Issue by dvrbts** [hmsc-r/HMSC#24]
Because `Hmsc-package.Rd` has an alias for `Hmsc`, when you request `?Hmsc` you get the package help page and not the function.  Since the function has numerous arguments it's essential to get `Hmsc.Rd` to load.

```
Hmsc 0.4.3.2
sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 18.10
    .     .     .     .
```

**Comment by jarioksa** [comment]
Dave,

This is a “known issue”, and I have suggested some alternatives to fix this, but nothing has been done yet.

What about filing a bug report in github?

Yes, I agree: there is a lot of bad coding practices. I haven’t started to clean those yet.

However, there is a difference between identical(XScale, FALSE) and !XScale: try with cases XScale <- NULL or XScale <- NA. Also have a look at the function isTRUE and its documentation. We (you and I) usually take care that arguments are coercible to logical (and not NA or NULL or list() or vector) in testing, but it needs some analysis of code to see that this is TRUE for the Hmsc code.

cheers, Jari

On 6 Sep 2019, at 12:33, Dave Roberts <notifications@github.com<mailto:notifications@github.com>> wrote:


Because Hmsc-package.Rd has an alias for Hmsc, when you request ?Hmsc you get the package help page and not the function. Since the function has numerous arguments it's essential to get Hmsc.RD to load.

Hmsc 0.4.3.2
sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Pop!_OS 18.10
. . . .

**Comment by jarioksa** [comment]
This is an issue that @MelindadeJonge already made in an email to the developers. Obvious solutions are
- edit the `Hmsc-package.Rd` file and remove the `alias{Hmsc}` line instead of using `devtools::document('.')`. I do think that it is a bit of **devtools** dogmatism to add a useless `R/Hmsc-package.R` file without any code just to be able to generate automatically a corresponding `man/Hmsc-package.Rd` file when you could directly write the latter.
- Another solution I suggested in an email was to rename the package to avoid name clashes in docs. This happens by changing the `Title:` line in `DESCRIPTION` – nothing else is needed.

**Comment by MelindadeJonge** [comment]
For now, I removed \alias{Hmsc} from the Hmsc-package.Rd file. Hmsc function help is available again through ?Hmsc.

**Comment by jarioksa** [comment]
I think this (and commit 5fee8f0d85fafb6529628b765ea078d11be74d87) fix this issue.
