### ISSUE TITLE
NAs in Y matrix cause MCMC error: Error in if (any(y < 0))

### ISSUE THREAD

**Issue by rburner** [hmsc-r/HMSC#38]
Hi - I'm trying to fit a hurdle model and so have set all 0s in my Y matrix to NA.

However, when I try to use sampleMcmc() I get the following error:

> m1 = sampleMcmc(t21L[[1]], thin = thin, samples = samples, transient = transient, 
            +     nChains = nChains, verbose = verbose, initPar = "fixed effects",nParallel = 1) 

[1] "Setting updater$Gamma2=FALSE due to specified phylogeny matrix"
[1] "Computing chain 1"
Hmsc::computeInitialParameter - initializing fixed effects with SSDM estimates

Error in if (any(y < 0)) stop("negative values not allowed for the 'Poisson' family") : 
  missing value where TRUE/FALSE needed

With some testing it looks like this is true even if I introduce a single NA to an otherwise functional Y matrix. But when I put NAs into a simulated example it doesn't give the error. What am I overlooking?

I have the latest github installation (reinstalled today).

Thanks!

**Comment by ovaskain** [comment]
So you are using a (possible lognormal) Poisson model. Are all non-NA values nonnegative integers?

Otso

Sent from my iPhone

On 17 Jan 2020, at 17.25, Ryan Burner <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi - I'm trying to fit a hurdle model and so have set all 0s in my Y matrix to NA.

However, when I try to use sampleMcmc() I get the following error:

m1 = sampleMcmc(t21L[[1]], thin = thin, samples = samples, transient = transient,
+ nChains = nChains, verbose = verbose, initPar = "fixed effects",nParallel = 1)

[1] "Setting updater$Gamma2=FALSE due to specified phylogeny matrix"
[1] "Computing chain 1"
Hmsc::computeInitialParameter - initializing fixed effects with SSDM estimates

Error in if (any(y < 0)) stop("negative values not allowed for the 'Poisson' family") :
missing value where TRUE/FALSE needed

With some testing it looks like this is true even if I introduce a single NA to an otherwise functional Y matrix. But when I put NAs into a simulated example it doesn't give the error. What am I overlooking?

I have the latest github installation (reinstalled today).

Thanks!

**Comment by rburner** [comment]
Otso,

Yes, that's correct, a lognormal Poisson model. I did just confirm that all of the Y matrix values are non-negative integers.

I just figured out the difference between my model and an example from the book (the book example _does_ work when I introduce NAs). The difference is that I am using 'initPar = "fixed effects" ' with my real data. If I remove this command from sampleMcmc() then it works on my data. So something in the glm functions must not like the NAs....

Thanks,

Ryan
