### ISSUE TITLE
prediction for poisson model

### ISSUE THREAD

**Issue by aplanillo** [hmsc-r/HMSC#4]
Hi, 

I tried running a model using poisson distribution (the response are counts of individuals). However, when I do the predictions of the model I get continuous numbers. Instead of 2 or 3 individuals, the models predicts 0.764534 individuals, for example. Thus, in some sites I end with a total abundance of 5 individuals and 10 species, which is hard to explain. Also, there is no site with a prediction of 0 individuals for any of the species.
Do you know how to interpret the predictions of the model, or better, how to get predictions that are integer numbers?

Thanks,
Aimara

**Comment by hmsc-r** [comment]
Did you have expected=TRUE in the arguments for the predict-function? If yes, you will get the expected count, which does not need to be an integer, so then this is a feature rather than a bug. If you set expected=FALSE, Poisson stochasticity will be included, and thus you will get integer-valued counts. Similarly, for probit models expected=TRUE gives occurrence probability (value between 0 and 1) whereas expected=FALSE gives actual occurrences that involve Bernoulli randomness (zeros or ones).

**Comment by gtikhonov** [comment]
Just to add a bit on @hmsc-r comment - if you really need to get just a single integer number, you have to make some decision on what property of the distribution you want to report. For example, you can make your predictions with `expected=FALSE`, get a bunch of integers, and then for each species take the value that was predicted most often - this would kind of correspond to the mode of posterior distribution. Alternatively, you can compute the median of those integers and this would be the median.
If you want to eliminate the Poisson observation model's stochastisity of the predictions made in such way, you can repeat each element of the `post` argument multiple times.

**Comment by aplanillo** [comment]
Ok, thanks for the quick response
