### ISSUE TITLE
Scaling the Y for normal observation model

### ISSUE THREAD

**Issue by gtikhonov** [hmsc-r/HMSC#51]
In commit 81d4273d5df08ec83ab0181a1a24e5d4724d254a#diff-d385a9a4c0892cbfdbaef4b4b3dc6fc7 @ovaskain introduced the potential scaling for the columns of Y matrix that are assigned with Gaussian observation model. The scaled object is constructed in the `Hmsc()` call and is used later during the sampling and predictions.
https://github.com/hmsc-r/HMSC/blob/afaf5212bfde9c4906bec43551a359faaaacc8cb/R/Hmsc.R#L646

But as far as I can judge based on the code, we never apply the inverse scaling. Is it a poorly documented feature or a bug?

**Comment by ovaskain** [comment]
If X and/or Tr are scaled, it is possible to transform all model 
parameters (beta, gamma, V) so that they correspond to the original 
units. This is not the case for Y, as at least based on my 
understanding/calculations it is not possible to back-transform all 
parameters so that they would correspond to those of model fitted to 
original Y. What is possible of course is to make predictions to 
original units, and this should be up and running, as the predict 
function includes the following code:

       for(i in 1:object$ns){
          m = object$YScalePar[1,i]
          s = object$YScalePar[2,i]
          if(m!=0 || s!=1){
             Z[,i] = Z[,i]*s + m
          }
       }

There is some discussion about this issue in the Ovaskainen and Abrego 
(2020) book in the chapter Bayesian inference in HMSC.

**Comment by gtikhonov** [comment]
Missed that part in the predict function, my bad.
