### ISSUE TITLE
Error in chol.default(W) : 'a' must have dims > 0

### ISSUE THREAD

**Issue by tinsman** [hmsc-r/HMSC#68]
This might very well be an issue with my data, so apologies in advance if that's the case. I get `Error in chol.default(W) : 'a' must have dims > 0` when I try to run the below model with spatial random effects:

I'm trying to run a model predicting presence-absence of three species using transect data. I've got GPS points for every observation and a transect number. I'd like to include both geographic location and transect as random effects. Every observation is a unique location (n = 169 in the full data set), but there were multiple observations per transect (n = 69). How do I properly set up the random effects when this is the case? 

I am able to run the model without random effects successfully, and I got the bird example working on my machine as well, so I suspect the issue is how I'm specifying my spatial random effect.

[Here's some data](https://drive.google.com/file/d/1Q-IGtqwN2XiuhYUmMgahfdog3oNifKaQ/view?usp=sharing), and here's what I've got so far code-wise. The first part is just loading everything in:

```
localDir = "."
data.directory = file.path(localDir, "data")
model.directory = file.path(localDir, "models")

library(Hmsc)
set.seed(1)

da = read.csv(file.path(data.directory, "example_data.csv"), stringsAsFactors=TRUE)
# Tell R transects are not a continuous variable
da$transect = as.factor(da$Transect_Numb)
# Remove records with NA for predictors
da = da[complete.cases(da[,c(5:10)]), ]
head(da)


XData = data.frame(id = da$ID, transect = da$transect,
                   height = da$IndHeightEstimation, dbh = da$DBH, veg = da$Vegetation_type,
                   uv = da$Understory_Visibility, elev = da$Elevation, park = da$park)
head(XData)

# Make a species occurence matrix
Y = as.matrix(da[,c(11:13)])
head(Y)

# I have difficulty whether the coordinates I use are in UTM 38S or WGS 1984
xy = as.matrix(cbind(da$POINT_X,da$POINT_Y))
colnames(xy)=c("x-coordinate","y-coordinate")
```

Here's where I think the issue arises:
```
studyDesign = data.frame(id = XData$id, transect = XData$transect)

rownames(xy)=studyDesign$id

# I'd like to be able to specify a random effect for space:
rLspat = HmscRandomLevel(sData = xy)
# and one for the particular transect, but this isn't as essential if I can do space.
rLtran = HmscRandomLevel(units = studyDesign$transect)



XFormula = ~ height + dbh + veg + uv + elev + park

m = Hmsc(Y=Y, XData = XData, XFormula=XFormula,
         distr="probit", studyDesign=studyDesign, ranLevels=list(id=rLspat, transect = rLtran))

m


nChains = 1
nParallel = 1
samples = 10
transient = 5
thin = 1
m1 = sampleMcmc(m, thin = thin, samples = samples, transient = transient,
                nChains = nChains, initPar = "fixed effects",
                nParallel = nParallel)
```
Thank you in advance for your help!

**Comment by jarioksa** [comment]
Sorry, but I can't reproduce this (and your data are inaccessible with message "you need access").

We have had some vague reports of this very same message earlier, but we have never been able to replicate those. I think in most cases users have fixed the problem in their own data, but I don't know how. We should add a check for this case in **Hmsc**, but currently I have no clue. There are four functions with this very same command, and I don't know where this error pops up and why.

**Comment by tinsman** [comment]
Hi thank you so much for your response. Here are the data I get the problem with as an .xlsx, which github lets you share.

[example_data.xlsx](https://github.com/hmsc-r/HMSC/files/5596322/example_data.xlsx)

**Comment by jarioksa** [comment]
This seems to be a tricky case to handle correctly. Basically the problem is that the `Hmsc` user-interface is very fragile (in particular after **R** changed default handling of factors vs. character strings where we had relied on the old behaviour). The model definition should be made *exactly* correct w.r.t. using factors, and if this fails, you get very confusing error messages. I think we need to make our user interface more robust as these wrong definitions are extremely difficult to get correct (except by chance and good luck) and also difficult to debug.

That was introduction. Now some steps towards solving the problem.

When you define your data frame `da`, you must tell explicitly that `id` is a factor:
```r
XData = data.frame(id = factor(da$ID), ...)
```
Then you must require that you also have factors in your `studyDesign`:
```r
studyDesign = data.frame(id = XData$id, transect = XData$transect, stringsAsFactors = TRUE)
```
After these, you will get rid of the error message.

Unfortunately, you will get a new error message:
```r
Error in chol.default(W) : 
  the leading minor of order 50 is not positive definite
```
You get this message because some of your spatial points are in identical positions:
```r
> which(duplicated(xy))
63 81 
32 50 
```
All spatial locations should be unique.

I didn't proceed with handling this issue, and therefore I do not know if fixing this second issue will solve all your problems.

As to your distances: "I have difficulty whether the coordinates I use are in UTM 38S or WGS 1984". Some of your coordinates are negative so they are not standard UTM coordinates. In standard UTM projections, the unit of coordinates is in meters from reference lines. The numeric values rather look like longitudes and latitudes, and they certainly are if your research site happens to be in Madagascar. You can use these in current **Hmsc** setting
```r
rLspat = HmscRandomLevel(sData = xy, longlat = TRUE)
```

**Comment by tinsman** [comment]
This worked! Thank you so much for your help.
