### ISSUE TITLE
sampleMcmc, some chains taking much longer than others

### ISSUE THREAD

**Issue by wilkesma** [hmsc-r/HMSC#69]
I am fitting a probit model to 101 taxa across 90,000 repeated observations from 15,000 sites sampled between 2002 and 2019. The random effects structure is sites nested within seasons (spring, autumn). The only fixed effect is time.

One of four chains completed in 74 hours, but the others are still running at 91 hours and counting. Tests on the same data with 30 total samples per chain went well, and other probit models with up to 40,000 repeated observations and 54 taxa have all worked fine.

Any suggestions please? Does the big difference in computation time between chains suggest an issue, or do I just need to be patient?

```
link="probit"
thin=10
samples=250
nChains=4
transient=50*thin
TrFormula = ~siz+res+fee

studyDesign <- data.frame(season=meta$season, site=meta$SITE_ID)
season <- HmscRandomLevel(units=studyDesign$season)
site <- HmscRandomLevel(units=studyDesign$site)
X.data <- data.frame(intercept=1, time=meta$days)
  
mod <- Hmsc(Y=taxa, XData=X.data, XFormula=~time, studyDesign=as.matrix(studyDesign),
              TrData=traits, TrFormula=TrFormula, phyloTree=tree,
              ranLevels=list("site"=site, "season"=season), distr=link)
mod.mcmc <- sampleMcmc(mod, samples = samples, thin = thin, transient = transient,
                         nChains = nChains, nParallel = nChains)
```

**Comment by ovaskain** [comment]
Different chains can take a different amount of time because they may 
choose (during the transient) a different number of latent factors. Use 
verbose if you need to see how the chains are processes (though does not 
work with nParallel=...). My main question which such big data would be 
that have you first fitted your models and done the analyses with a 
smaller subset of data? I always recommend doing first the analyses with 
a subset that goes through fast, the producing all results and writing 
the first draft of the ms based on that, and only then running the final 
runs (e.g. while the first draft is with co-authors). Following this 
strategy usually saves time as it avoids repeated long waiting times 
(e.g. you fit the big model and then realize that something should be 
changed).

Otso

**Comment by wilkesma** [comment]
Thank you, Otso. The last chain took twice as long as the first chain, which I was not expecting. I now have another problem reading the model object back in to compute predicted values. I will raise another issue.
