### ISSUE TITLE
constructGradient error

### ISSUE THREAD

**Issue by elslabbert** [hmsc-r/HMSC#71]
Hi HMSC team,
I am using the script pipeline from the recent HMSC course, thanks for the very nice pipeline!. I have now encountered an error at the last script (S8) at the   
'<Gradient = constructGradient(m,focalVariable = covariate)>' step for both categorical and numeric XData variables. 

Error for the categorical covariate:
>Error in seq.default(mi, ma, length.out = ngrid) : 
 > 'from' must be a finite number
>In addition: Warning message:
>In seq.default(mi, ma, length.out = ngrid) : NAs introduced by coercion

Error for the numeric covariate:
>Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
>  NA/NaN/Inf in 'y'
>In addition: Warning message:
>In storage.mode(v) <- "double" : NAs introduced by coercion

Where and how should I trouble shoot this error? I tried looking over the internal code for this command, but was not able to make much progress in understanding where the issue arises.

Thanks in advance for your inputs!

**Comment by jarioksa** [comment]
It seems that you have missing data in your `X`-variates (covariates). Both of your error messages point out the same problem of `NA` values. I don't know where this happened, as we do not accept missing values in covariates in `Hmsc` models, but issue and error message it these are found. I cannot reproduce this as I cannot produce `Hmsc` models with missing data in covariates, but I need more information.

**Comment by elslabbert** [comment]
@jarioksa, Thanks for the prompt input. The model to this point passed all the 'checks and balances' for setting up an Hmsc model. With no NA's in the raw XData, so the error was baffeling to be reporitng NA's. Could I send you the fitted model to have a more in-depth look?

**Comment by jarioksa** [comment]
@elslabbert Please do so. You may also have a quick look yourself: if your model is called `m`, the data used in `constructGradient` are in `m$XData` that should not contain any `NA`, `Inf` or `-Inf` (which usually come from data transformations: `log(0)`  gives `-Inf`).

**Comment by elslabbert** [comment]
@jarioksa I checked my XData from my model  for NA'S with apply(models[[1]]$XData, 2, function(x) any(is.na(x))) and get them all to be FALSE, so not NA's. I have a log transformation of one variable, but use log(variable+1) due to the presence of some zero values. I sent you an example of my model to you g-mail. Thanks for your help looking into this.

**Comment by jarioksa** [comment]
The problem is that your first variable `Land_use` should be a factor, but it is not: it is a character string variable. Most functions handle this similarly as a factor, but some are pickier, `lm` is the picky one in this case, and cannot handle a linear model where the response variable (`non.focalVariable`) is a character string when it is expecting a number. Naturally, we should not use `lm` for character variables, and for factors we indeed use multinomial model – but there were no factors in your data.

This is the reason why we say that you should use `stringsAsFactors=TRUE` when you read in your data. If you still have non-factor data (character or numeric), where you should have factors, change them to factors and refit your models. You can use either of these two methods depending on your taste (and there are more methods):
```r
X$Land_use = as.factor(X$Land_use)
X = within(X, Land_use <- as.factor(Land_use))
```

It seems that we need to develop data checking. We have three current reports on trouble caused by non-factor variables when factors were expected (#68, #70) and in addition one with picky `lm` in `constructGradient` (#65).

**Comment by elslabbert** [comment]
Oh yes, thanks @jarioksa I see I missed adding this when I was reading in my data. It is indeed an important aspect to not miss in the data checking and model set-up phase already. Thanks for pointing this out! 
As you suggest, it would be helpful to have a warning about this earlier on in the pipeline.
